export const ADD_PRODUCT_TO_CHECKOUT = 'ADD_PRODUCT_TO_CHECKOUT';
export const REMOVE_PRODUCT_FROM_CHECKOUT = 'REMOVE_PRODUCT_FROM_CHECKOUT';
export const UPDATE_PRODUCT_FROM_CHECKOUT = 'UPDATE_PRODUCT_FROM_CHECKOUT';
