export const ADD_PRODUCT_TO_CHECKOUT = 'ADD_PRODUCT_TO_CHECKOUT';
export const REMOVE_PRODUCT_FROM_CHECKOUT = 'REMOVE_PRODUCT_FROM_CHECKOUT';
export const UPDATE_PRODUCT_FROM_CHECKOUT = 'UPDATE_PRODUCT_FROM_CHECKOUT';
export const REMOVE_ALL_PRODUCTS_FROM_CHECKOUT =
	'REMOVE_ALL_PRODUCTS_FROM_CHECKOUT';

export const INITIALIZE_USER_DETAILS = 'INITIALIZE_USER_DETAILS';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS';
export const SET_USER_ORDERS = 'SET_USER_ORDERS';
export const UPDATE_USER_ORDERS = 'UPDATE_USER_ORDERS';

export const SET_SEARCHED_TEXT = 'SET_SEARCHED_TEXT';

export const TOGGLE_MENU = 'TOGGLE_MENU';
